apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: weatherapp-weather
  namespace: argocd
  labels:
    app.kubernetes.io/name: weatherapp
    app.kubernetes.io/component: weather-service
    app.kubernetes.io/part-of: weatherapp
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/khaledhawil/WeatherApp-CI-CD-Pipeline.git
    targetRevision: HEAD
    path: kubernetes/weather
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
